## YAML Template.
---
language: php
branches:
  only:
    - master
    - development
    - v0.1.0
    - v0.2.0a-development
php:
  - 5.4
script: phpunit --configuration ./tests/SprayFireTest/travis_configuration.xml

